name: Pro

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  release:
    types:
      - created

jobs:
  callVersion:
    uses: ./.github/workflows/reusable_version.yml
  
  callBuild:
    needs: [callVersion]
    uses: ./.github/workflows/reusable_build.yml
    with:
      NUGETVERSIONV2: ${{ needs.callVersion.outputs.NUGETVERSIONV2 }}  