name: Reusable build

on:
  workflow_call:
    inputs:
      NUGETVERSIONV2:
        required: true
        type: string

env:
  Configuration: Release 
  SlnPath: ./src/Svea.WebPay.SDK.sln
  CsprojPath: ./src/Svea.WebPay.SDK/Svea.WebPay.SDK.csproj
  dotnetVersion: |
    3.1.101
    5.x
    6.x
  AZURE_WEBAPP_PACKAGE_PATH: '.'

jobs:
  build:
    name: Build SDK ${{ inputs.NUGETVERSIONV2 }}
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
    
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.dotnetVersion }}
 
      - name: Install dependencies
        run: dotnet restore ${{ env.SlnPath }}
 
      - name: Publish Sdk Sample site
        run: dotnet publish --configuration ${{ env.Configuration }} -p:Version=${{ inputs.nuGetVersionV2 }} --no-restore src/Samples/Sample.AspNetCore/Sample.AspNetCore.csproj --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/samplesite'

      - name: Archive Sample.AspNetCore
        uses: actions/upload-artifact@v3
        with:
          name: Sample.AspNetCore
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/samplesite

      - name: Publish Sdk Sample site system test
        run: dotnet publish --configuration ${{ env.Configuration }} -p:Version=${{ inputs.nuGetVersionV2 }} --no-restore src/Samples/Sample.AspNetCore.SystemTests/Sample.AspNetCore.SystemTests.csproj --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/systemtests'

      - name: Archive Sample.AspNetCore.SystemTests
        uses: actions/upload-artifact@v3
        with:
          name: Sample.AspNetCore.SystemTests
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/systemtests

      - name: Nuget pack
        run: dotnet pack ${{ env.CsprojPath }} -p:PackageVersion=${{ inputs.NUGETVERSIONV2 }} -p:Version=${{ inputs.NUGETVERSIONV2 }} --configuration=${{ env.Configuration }} --output=artifacts

      - name: Archive nuget packages artifacts
        uses: actions/upload-artifact@v3
        with:
          # Artifact name
          name: packages
          # A file, directory or wildcard pattern that describes what to upload
          path: artifacts/*.nupkg