name: Uat

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    branches:
      - release/**
      - hotfix/**

jobs:
  callVersion:
    uses: ./.github/workflows/reusable_version.yml
  
  callBuild:
    needs: [callVersion]
    uses: ./.github/workflows/reusable_build.yml
    with:
      NUGETVERSIONV2: ${{ needs.callVersion.outputs.NUGETVERSIONV2 }} 